### ISSUE TITLE
Slimes? :)

### ISSUE THREAD

**Issue by atlgeek007** [MarkusBordihn/BOs-Easy-Mob-Farm#1]
**Is your feature request related to a problem? Please describe.**
Is there any chance we can get minecraft slimes added to the allowed list for the plains farm? Or would this be better for a swamp farm, along with a witch?

Either way, a slime farm would be very helpful in 1.18.2 since there's no tinkers (yet) or Industrial Foregoing (yet)

**Describe the solution you'd like**
A swamp hostile farm with the ability to do both Witches and Slimes?

**Comment by MarkusBordihn** [comment]
Thanks for the suggestion. I will add a swamp mob farm and the possibility to customize the allow list over the config file.
This should cover all possible use-cases even for custom mobs without using the creative mob farm.

I still need to run some tests, but this should be live in the next few days.

**Comment by MarkusBordihn** [comment]
The swamp farm and a witch bottle to capture a witch / slime is released under https://www.curseforge.com/minecraft/mc-mods/easy-mob-farm/files/3786270 .

This new versions allows to adjust the catchable and farmable mobs over config files, so you can easily customize all mob farms and catching items to your needs.

**Comment by atlgeek007** [comment]
I installed the updated version, went out and caught a slime, but it doesn't drop anything in the swamp farm.

The witch does, which is great!

**Comment by MarkusBordihn** [comment]
Keep in mind that only small slimes drop something.
Bigger slimes drop nothing, so you need to make them smaller before
catching and putting them in a farm.

Christopher McCoy ***@***.***> schrieb am Di., 10. Mai 2022,
22:13:

**Comment by atlgeek007** [comment]
okay, I let the slime out of the cage and re-captured one of the small ones.  I'll try that!
