### ISSUE TITLE
[Bug/typo] Loot Enhancement tooltip is not consistent with wiki.

### ISSUE THREAD

**Issue by Ynaught** [MarkusBordihn/BOs-Easy-Mob-Farm#101]
### **Wiki:**
![image](https://github.com/user-attachments/assets/b72739e6-3482-45af-a05a-005fbbcce645)

### **Tooltip:**
![image](https://github.com/user-attachments/assets/027b1d96-bf5a-4a8d-9cc3-1c88467b10ad)

### **==================================================================**

Is the loot enhancement supposed to enhance the "quantity" of drops as it says on the wiki or does it enhance the "quality" of drops as said in the tool tip?

Mod file version:
easy_mob_farm-neoforge-1.21.4-8.8.0

**Comment by Ynaught** [comment]
Also, unrelated, but I can't tell which is more efficient for gold farming zombie piglins, 4 speed enhancements or 4 loot enhancements? I'm guessing "luck" doesn't matter here? I'm not even sure how it effects things outside of wither skulls, tools and armor.

**Comment by joel4848** [comment]
> Also, unrelated, but I can't tell which is more efficient for gold farming zombie piglins, 4 speed enhancements or 4 loot enhancements? I'm guessing "luck" doesn't matter here? I'm not even sure how it effects things outside of wither skulls, tools and armor.

Firstly, well spotted on the inconsistency between in-game and the wiki. I think the wiki is right - I'd been looking at the loot upgrade and luck upgrade in-game and thinking "... what does 'upgrades the quality' mean?!" and seeing the wiki says 'quantity' makes a lot more sense.

Secondly re. not knowing what upgrade is more efficient for farming gold from zombie piglins, I completely agree that it's way too unclear. I'm currently trying to farm iron from a zombie capture card, I've got three different zombie capture cards that don't stack, two don't seem to drop iron at all and one does but VERY slowly.

It would be great to have a button in the farm UI that brings up a second panel which tells you what the current farm/card/upgrade setup drops will be, and their odds - so you can experiment with different combos to find the most efficient one.

**Comment by MarkusBordihn** [comment]
Thanks so much for your valuable feedback! I'll make sure to update the descriptions to clarify the functionality and make it clear what's happening behind the scenes.

Additionally, I'll conduct tests to explore the feasibility of adding a loot preview feature. The main challenge with implementing a loot preview is that it can only be generated on the server side and requires multiple loot simulations to cover all possible outcomes.

In the past, this approach has caused micro-lags, so I'll investigate whether it's possible to generate the preview during the capture card creation process and store it directly in the capture card. However, this would result in a static preview, meaning any changes to the loot table after the card is created would not be reflected in the preview. I'll do my best to find a balance between functionality and performance to improve the player experience!

**Comment by Ynaught** [comment]
Replying to JW

Yeah, drop rates would be nice info. You know how there is an [ i ] icon on a mob farm ui where if you hover your mouse over it, it gives you info? I would love a second box that gives drop-rate intel for each item in that mobs loot table. Idk what the icon would look like though, but I would def want it to be separate from the base info box. Maybe something like this with the bundle icon:
![image](https://github.com/user-attachments/assets/b75ce5f8-2ffc-406e-8f8c-10146f2c9bda)

or 

![image](https://github.com/user-attachments/assets/e4ea410f-ba35-494e-b3fd-3848e5c52afa)

That being said, why are you not using a crystal ball on an iron golem to capture it? It's a much more reasonable way to iron farm. If you use fire to get it to low health _(fire charge, flint and steal, lava bucket)_, it won't even attack you.
