### ISSUE TITLE
[Bug] Duplication

### ISSUE THREAD

**Issue by collemi** [MarkusBordihn/BOs-Easy-Mob-Farm#105]
When we use a card or a upgrade with a right click on a farm block it put the card/upgrade inside but the game does not take one from my hand
![2024-12-18_20 22 53](https://github.com/user-attachments/assets/0b34f308-b85c-4c27-9d95-aa1397ecb1cc)
![2024-12-18_20 23 14](https://github.com/user-attachments/assets/f9c18956-093a-4fb5-a2a6-a540e8e51365)
![2024-12-18_20 23 24](https://github.com/user-attachments/assets/e341ee53-4b7c-4492-8cec-858e1464af6d)

**Comment by MarkusBordihn** [comment]
Please provide the following details:  
- **Mod Loader** you are using (e.g., Fabric, Forge, NeoForge).  
- **Minecraft version** (e.g., 1.18.2, 1.19.2, 1.20.1, etc.).  
- **Mod version** (e.g., 8.7.x, 8.8.x, 8.9.x, etc.).  

Thank you very much!

**Comment by collemi** [comment]
im using neoforge 21.1.80 in minecraft 1.21.1 and the mod version is 8.9.0

**Comment by MarkusBordihn** [comment]
Thank you for providing the details! 
I was able to quickly reproduce the issue and identified a typo as the cause.

Version 8.9.1 with the fix will be live within the next few minutes.

**Comment by Ynaught** [comment]
Hey, I noticed v8.9.2 didn't have a changelog. What was changed in it?

**Comment by MarkusBordihn** [comment]
> Hey, I noticed v8.9.2 didn't have a changelog. What was changed in it?

Please avoid reopening or commenting on closed issues.  

Version **8.9.2** is a quick fix aimed at testing specific crash scenarios with mob capture cards.

For more information, you can refer to this comment:  
🔗 [Issue #110 - Comment](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues/110#issuecomment-2561487684)

Once this quick fix is confirmed and refined into a proper solution, a changelog will be created and uploaded to GitHub.  

In some cases, I upload quick-fix versions to Modrinth and CurseForge to address issues that I can't reproduce directly. 
If the fix proves effective, I update the changelog accordingly. 
Until then, it wouldn’t be helpful to include vague notes like "testing various fixes for crashes." 😊
