### ISSUE TITLE
[Bug] The ghast is too big 😢 

### ISSUE THREAD

**Issue by collemi** [MarkusBordihn/BOs-Easy-Mob-Farm#107]
1.21.1 - neoforge-21.180 - 8.9.1
the ghast is very big and can't see our beautiful drops
you juste have to put the card or a capture item with the ghast in a farm
![2024-12-20_23 22 14](https://github.com/user-attachments/assets/250d470a-255f-4cef-b7ee-7a650bc495cf)

**Comment by Vadewolf** [comment]
btw its not just the ghast but the elder gardian too

**Comment by MarkusBordihn** [comment]
Thank you for the report! This issue has been fixed and will be included in the next update. 

![image](https://github.com/user-attachments/assets/78dfc90d-daf1-4d1b-87e4-c2e1d734799d)

![image](https://github.com/user-attachments/assets/6d839ece-ea1a-4132-89d0-ca3fcaf44085)

**Comment by Vadewolf** [comment]
sweet thank you so much
