### ISSUE TITLE
Mobs "escape" out of the farm and spawn next to it

### ISSUE THREAD

**Issue by TheToastbeat** [MarkusBordihn/BOs-Easy-Mob-Farm#109]
**Minecraft and Mod version** 🐞
MInecraft Fabric 1.19.2, Mod Version: easy_mob_farm-fabric-1.19.2-8.9.1

**Describe the bug** 🐞
After leaving the Chunk or area where the Mobfarm is placed and I come back. It happens, that the mob "escaped" the farm. It is leaving the slot for the capture card empty and the mob spawned next to the farm. I used the "Lucky Drop Farm Tier 3"

**To Reproduce** ⚙️

1. Place a Capture Card in the Mobfarm (Happend with the Evoker and the Enderwarthog (AdventureZ Mod))
2. Leave the Chunk or Area
3. Come back to the Chunk or Area
4. The Mob spawned next to the farm and wasn´t inside the farm anymore

**Expected behavior** ✔️
I expected the mob to stay inside the farm.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)** 🧩

AdditionalStructures-1.19.x-(v.4.1.2-fabric).jar

advancednetherite-fabric-1.6.7-1.19.2.jar

advdebug-2.3.0.jar

adventurez-1.4.18.jar

alternate-current-mc1.19-1.7.0.jar

another_furniture-fabric-1.19.2-2.1.4.jar

architects-palette-fabric-3.0.0.jar

architectury-6.5.85-fabric.jar

AttributeFix-Fabric-1.19.2-17.2.7.jar

balm-fabric-1.19.2-4.6.0.jar

BarteringStation-v4.0.3-1.19.2-Fabric.jar

bclib-2.1.8.jar

better-end-2.1.7.jar

better-nether-7.1.5.jar

betterchunkloading-fabric-1.19.2-2.3.jar

BetterCompatibilityChecker-Fabric-2.0.2-build.16+mc1.19.1.jar

betterfpsdist-fabric-1.19.2-3.7.jar.disabled

betterstats-2.9.3+1.19.2.jar

BetterTridents-v4.0.2-1.19.2-Fabric.jar

biomemakeover-FABRIC-1.19.2-1.6.4.jar

biomemusic-fabric-1.19.2-2.2.jar

BoatBreakFix-Universal-1.0.2.jar

BOMD-1.4.8-1.19.2.jar

Bookshelf-Fabric-1.19.2-16.3.20.jar

BountifulFabric-4.0.0.jar

BuildingWands-mc1.19.2-2.6.9-release.jar

bygonenether-1.19-1.3.2.jar

carryon-fabric-1.19.2-2.1.1.22.jar

charm-fabric-1.19.2-4.4.4.jar

charmofundying-fabric-6.2.1+1.19.2.jar

chefs-delight-1.0.3-fabric-1.19.2.jar

chunksending-fabric-1.19.2-2.6.jar

cleancut-6.0.jar

clientcrafting-fabric-1.19.2-1.6.jar

cloth-config-8.3.103-fabric.jar

Clumps-fabric-1.19.2-9.0.0+14.jar

collective-1.19.2-7.7.jar

comforts-fabric-6.0.6+1.19.2.jar

configured-fabric-2.0.0-1.19.2.jar

connectivity-fabric-1.19.2-4.5.jar

copycats-2.1.4+mc.1.19.2-fabric.jar

CorgiLib-fabric-1.19.2-1.0.0.34.jar

crawl-0.11.1.jar

create_ultimate_factory-1.8.0-fabric-1.19.2.jar

create-fabric-0.5.1-i-build.1630+mc1.19.2.jar

createaddition-fabric+1.19.2-1.2.3.jar

createoreexcavation-fabric-1.19-1.2.3.jar

cultural-delights-fabric-0.14.10+1.19.2.jar

cupboard-fabric-1.19.2-2.1.jar

DarkPaintings-Fabric-1.19.2-13.1.5.jar

dawn-3.5.0.jar

Debugify-2.8.0.jar

Decorative Blocks-fabric-1.19.2-3.1.1.jar

deeperdarker-fabric-1.19.2-1.2.3.jar

DEUF_Refabricated-MC1.19.2-1.0.0.jar

DiagonalFences-v4.2.6-1.19.2-Fabric.jar

dragonloot-1.1.2.jar

DungeonsArise-1.19.2-2.1.56-fabric-beta.jar

easy_mob_farm-fabric-1.19.2-8.9.1.jar

EasyAnvils-v4.0.11-1.19.2-Fabric.jar

EasyMagic-v4.3.3-1.19.2-Fabric.jar

ecologics-fabric-1.19.2-2.1.11.jar

elytraslot-fabric-6.1.1+1.19.2.jar

Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0.jar

entity_texture_features_fabric_1.19.2-4.6.1.jar.disabled

everycomp-1.19.2-2.5.14-fabric.jar

expandeddelight-0.2.5.2.jar

explorify-fabric-1.19-1.3.0.jar

fabric-api-0.77.0+1.19.2.jar

fabric-language-kotlin-1.10.14+kotlin.1.9.20.jar

fabric-seasons-2.3+1.19.jar

fabric-seasons-byg-2.0.1.1-compat-1.0.jar

fabric-seasons-delight-1.3.9-compat-1.0.jar

fabric-seasons-extras-1.2-BETA+1.19.jar

fabric-seasons-terraformers-compat-1.0.jar

FallingTree-1.19.2-3.10.1.jar

farmers-delight-fabric-mc1.19-1.19.2-1.3.10.1.jar

farmersknives-2.4.1.jar

fastpaintings-1.19-1.1.2-fabric.jar

ferritecore-5.0.3-fabric.jar

ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar

frame-0.26.2+1.19-fabric.jar

friendsandfoes-fabric-mc1.19.2-1.8.10.jar

frostiful-0.5.8 (1).jar

ftb-library-fabric-1902.4.1-build.236.jar

ftb-quests-fabric-1902.5.6-build.304.jar

ftb-teams-fabric-1902.2.14-build.123.jar

ftb-xmod-compat-fabric-1.2.3.jar

fullstackwatchdog-1.0.1+1.19.2-fabric.jar

Galosphere-1.19.2-1.3.0-Fabric.jar

geckolib-fabric-1.19-3.1.40.jar

geophilic-1.19-2.0.0c.jar

go-fish-1.6.0-1.19.1.jar

goblintraders-fabric-1.8.1-1.19.2.jar

goodall-1.2.0-fabric.jar

gpumemleakfix-fabric-1.19.2-1.6.jar

Grass_Overhaul-Fabric-23.05.28_MC1.17.1-1.19.2.jar

guardvillagers-2.0.6-1.19.2.jar

handcrafted-fabric-1.19.2-2.0.6.jar

Iceberg-1.19.1-fabric-1.0.46.jar

immersive_weathering-1.19.2-1.2.10-fabric.jar

inmis-2.7.1-1.19.jar

inmisaddon-1.0.4.jar

item-filters-fabric-1902.2.9-build.51.jar

Jade-1.19.1-fabric-8.7.3.jar

jamlib-0.6.1+1.19-1.19.2.jar

jumpoverfences-fabric-1.19.2-1.1.1.jar

Kambrik-4.0-1.19.2.jar

Kiwi-1.19.1-fabric-8.3.4.jar

kleeslabs-fabric-1.19.2-12.3.0.jar

konkrete_fabric_1.6.1_MC_1.19.1-1.19.2.jar

krypton-0.2.1.jar

LeavesBeGone-v4.0.1-1.19.2-Fabric.jar

letmedespawn-1.18.x-1.19.x-fabric-1.0.2.jar

letsdo-api-fabric-1.1.0.jar

letsdo-meadow-fabric-1.2.4.jar

letsdo-vinery-fabric-1.3.12.jar

lithium-fabric-mc1.19.2-0.11.1.jar

lmft-1.0.2+1.19-fabric.jar

lootintegrations-fabric-1.19.2-3.2.jar

MagnumTorch-v4.2.3-1.19.2-Fabric.jar

mcw-fences-1.1.2-mc1.19.2fabric.jar

mcwfencesbyg-fabric-1.19.2-1.3.jar

memoryleakfix-fabric-1.17+-1.1.2.jar

memorysettings-fabric-1.19.2-5.3.jar

midnightlib-fabric-1.0.0.jar

minecells-1.5.8 (1).jar

MobCatcher-Fabric-1.19.2-1.2.15.jar

modernfix-fabric-5.18.1+mc1.19.2.jar

modpack-update-checker-1.19.2-fabric-0.10.1.jar.disabled

moonlight-1.19.2-2.3.5-fabric.jar

naturalist-fabric-4.0.3-1.19.2.jar

NaturesCompass-1.19.2-2.1.0-fabric.jar

Necronomicon-Fabric-1.3.0.jar

neruina-1.3.0-fabric+1.18.2-1.20.1.jar.disabled

NetherChested-v4.0.4-1.19.2-Fabric.jar

netherdepthsupgrade-fabric-3.1.1-1.19.2.jar

netherportalfix-fabric-1.19-10.0.1.jar

NethersDelight-1.0.1.jar

NightConfigFixes-v4.0.7-1.19.2-Fabric.jar

NoChatReports-FABRIC-1.19.2-v1.13.12.jar

Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.6.jar

onsoulfire-1.19-2.jar

open-parties-and-claims-fabric-1.19.2-0.20.0.jar

owo-lib-0.9.3+1.19.jar

oxidized-1.7.2.jar

Paintings-fabric-1.19.2-10.2.4.0.jar

paradise-lost-2.1.0-beta+1.19.2.jar

Patchouli-1.19.2-77-FABRIC.jar

Paxi-1.19.2-Fabric-3.0.1.jar

Ping-Wheel-1.7.0-fabric-1.19.2.jar

plushie-mod-1.2.jar

polymorph-fabric-0.46.5+1.19.2.jar

promenade-2.7.1.jar

Public GUI Announcement-fabric-1.19.2-4.3.3.jar

PuzzlesLib-v4.4.3-1.19.2-Fabric.jar

quartz-elevator-2.1.5+1.19.jar

rainbowlamp-fabric-1.1-1.19.X.jar

reacharound+1.19-1.1.2.jar

recipeessentials-fabric-1.19.2-3.2.jar

redirectionor-1.19.2-3.3.2-fabric.jar

repurposed_structures_fabric-6.3.28+1.19.2.jar

rer-2.6.0.jar

resourcefullib-fabric-1.19.2-1.1.24.jar

rhino-fabric-1902.2.2-build.280.jar

right-click-harvest-3.2.3+1.19.x-1.20.1-fabric.jar

rottencreatures-fabric-1.19.2-1.0.1.jar

RoughlyEnoughItems-9.1.668.jar

RoughlyEnoughLootTables-1.19-1.0.jar

RoughlyEnoughProfessions-fabric-1.19.2-1.1.4.jar

ServerBrowser-1.19.2-FABRIC-1.1.0.jar

sliceanddice-fabric-2.6.1.jar

smarterfarmers-1.19.2-1.7.2-fabric.jar

smoothchunk-fabric-1.19.2-3.5.jar

snow-under-trees-fabric-1.0.0+1.19.2.jar

SnowRealMagic-1.19.2-fabric-5.1.2.jar

snowyspirit-1.19.2-2.1.13-fabric.jar

sodium-fabric-mc1.19.2-0.4.4+build.18 (1).jar

sound-physics-remastered-fabric-1.19.2-1.4.5.jar

spark-1.9.42-fabric.jar

sparsestructures-2.1.jar

spirit-fabric-1.19.2-2.2.6.jar

starlight-1.1.1+fabric.ae22326.jar

starterkit-1.19.2-5.3.jar

Stoneworks-v4.0.1-1.19.2-Fabric.jar

Strawgolem-fabric-1.19.2-2.0.0-beta.5.jar

Structory_Towers_1.19_v1.0.1.jar

Structory-1.19-v1.3.jar

structureessentials-fabric-1.19.2-3.2.jar

supplementaries-1.19.2-2.4.11-fabric.jar

takesapillage-1.19-1.0.4.jar

TerraBlender-fabric-1.19.2-2.0.1.136.jar

terrestria-5.0.12.jar

the_bumblezone_fabric-6.7.42+1.19.2.jar

thermoo-1.4.1.jar

thonkutil-2.15.4+1.19.jar

toms_storage_fabric-1.19-1.5.9.jar

Towns-and-Towers-1.19.2-1.9.jar

TradingPost-v4.2.0-1.19.2-Fabric.jar

transparent-5.1.2+1.19-fabric.jar

trinkets-3.4.2.jar

twigs-3.0.0-fabric-1.19.2.jar

twilightforest-fabric-1.19.2-4.2.357.jar

universal_ores-1.4.2.jar

variantcraftingtables-3.3.3.jar

veinmining-fabric-1.1.3+1.19.2.jar

villagernames-1.19.2-7.0.jar

VillagersPlus_1.9.2_(FABRIC)_for_1.19.2.jar

VisualWorkbench-v4.2.4-1.19.2-Fabric.jar

voidtotem-fabric-1.19.2-2.1.0.jar

voidz-1.0.9.jar

winterly-0.8.3.jar

wolf-armor-compat-1.0.3-1.19.2.jar

wolves-with-armor-1.8.0-1.19.jar

wondrouswilds-1.19.2-1.1.6.jar

wraith-waystones-3.0.8+mc1.19.2.jar

Xaeros_Minimap_23.8.4_Fabric_1.19.1.jar

XaerosWorldMap_1.36.0_Fabric_1.19.1.jar

xlpackets-1.19.2-4.jar

xp_storage-1.4.3+1.19.jar

xpstorage_trinkets-0.1+1.19.jar

YetAnotherConfigLib-2.2.0-for-1.19.2.jar

youre-in-grave-danger-1.4.9.jar

YSNS-FFQ-1.0.3.jar

YungsApi-1.19.2-Fabric-3.8.10.jar

YungsBetterDungeons-1.19.2-Fabric-3.2.1.jar

YungsBetterEndIsland-1.19.2-Fabric-1.0.jar

YungsBetterJungleTemples-1.19.2-Fabric-1.0.1.jar

YungsBetterMineshafts-1.19.2-Fabric-3.2.0.jar

YungsBetterNetherFortresses-1.19.2-Fabric-1.0.6.jar

YungsBetterOceanMonuments-1.19.2-Fabric-2.1.1.jar

YungsBetterStrongholds-1.19.2-Fabric-3.2.0.jar

YungsBetterWitchHuts-1.19.2-Fabric-2.1.0.jar

YungsBridges-1.19.2-Fabric-3.1.0.jar

****

Thank you already for your help :)

**Comment by MarkusBordihn** [comment]
Thank you for the report!  

This behavior is **intentional** and not a bug or issue. For more details, please refer to the official documentation:  
🔗 https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/wiki/MobFarm#-lucky-drop-farm

**Explanation:**  
The Lucky Drop Farm is a unique type of Mob Farm designed to generate rare and valuable drops. 
However, as part of its mechanics, there is a **5% chance** that the mob may escape, leaving the capture card slot empty and spawning the mob nearby.  

This adds an element of risk and excitement to the Lucky Drop Farm, making it distinct from other mob farms. 
If you prefer a farm without this mechanic, consider using a different type of Mob Farm from the mod.

**Comment by TheToastbeat** [comment]
Oh, I didn't knew that. I will use another type then. Thank for developing this great Mod!
