### ISSUE TITLE
[Bug] Xray glitch with Mob farm

### ISSUE THREAD

**Issue by dustin7789** [MarkusBordihn/BOs-Easy-Mob-Farm#114]
**Note**:
Please make sure to fill out the following template to the best of your ability. This will help us
to identify and fix the issue faster.

**Minecraft and Mod version** 🐞
1.21.4. Mod version 8.9.2 For NeoForge version 21.4.47

**Describe the bug** 🐞
See through world when mob farm is placed down against solid block

**To Reproduce** ⚙️
Place tier 3 mob farm down with a side against a block and see through world.

**Expected behavior** ✔️
not to have an xray glitch

![2024-12-29_18 14 04](https://github.com/user-attachments/assets/23256426-7e15-4df8-932d-9a9c2154f1b5)

***
I tested with no other mods and still happens.

**Comment by MarkusBordihn** [comment]
Thank you for the report!

I wasn't able to reproduce the issue on my end using the 21.4.47-beta NeoForge version.

![image](https://github.com/user-attachments/assets/d2a51856-56ca-46f9-9d4e-05d054a65254)

![image](https://github.com/user-attachments/assets/935acd06-bb15-46e7-88c2-d380645e7c38)

Could you let me know if you're using any shaders or mods that modify block rendering (such as block culling or visual enhancements)? 

If so, please try placing the mob farm without those enabled to see if the issue persists.  

Let me know the results, and I’ll be happy to investigate further!
