### ISSUE TITLE
[Bug] Your title here

### ISSUE THREAD

**Issue by susgirl446** [MarkusBordihn/BOs-Easy-Mob-Farm#116]
**Note**:
Please make sure to fill out the following template to the best of your ability. This will help us
to identify and fix the issue faster.

**Minecraft and Mod version** 🐞
Minecraft: Fabric 1.21.1 
Easy Mob Farm: v8.9.1

**Describe the bug** 🐞
Mob capture cards dont stack

**To Reproduce** ⚙️

Kill a few mobs until you have a few capture cards and then put them into a chest.

**Expected behavior** ✔️
That they all stack into 1 slot

**Screenshots** 📸
![2024-12-30_19 51 41](https://github.com/user-attachments/assets/bb3e3377-87e3-4e80-a13d-fd5f65e7be38)
(they where shift clicked into the chest)

**Debugging** 🛠️
Before reporting an issue, please enable the debug mode over `/easy_mob_farm debug log true` to get
more <- This errors 'incorrect argument'
detailed information about the issue in the logs.
Additionally, check if there is anything relevant in the crash-reports, debug.log, and latest.log
file. <- It is just initializing from what i read

**Is the issue happening in combination with other mods? (If yes, please provide a full list)** 🧩
i tried it with isolating the mod so no. its not a compatibility issue

**Additional context** 📝

**Comment by MarkusBordihn** [comment]
Duplication of https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues/102
