### ISSUE TITLE
[Suggestion] Ability to acquire mob drops that require a 'player kill' or other situational requirement

### ISSUE THREAD

**Issue by AerosAtar** [MarkusBordihn/BOs-Easy-Mob-Farm#12]
Something that I feel is missing compared to some other mob farm-style mods is the ability to acquire drops from mobs that require it to be a 'player kill' rather than another method (environmental damage, etc), or those requiring special circumstances. For example, a Zombie Heart from the Reliquary mod or a music disc from a skeleton killing a creeper.

I further suggest that this could be done either as a permanent change (it just does it automatically), via a configuration option or 'installable upgrade(s)'.

**Comment by MarkusBordihn** [comment]
Thanks for the feedback, like the idea with the additional upgrade slot. 👍

**Comment by MarkusBordihn** [comment]
This feature was be added with the latest version, so I will close this feature request.
