### ISSUE TITLE
[Mod Support] forbidden arcanus 1.18.2/ 1.19.2

### ISSUE THREAD

**Issue by FullMetalMaster** [MarkusBordihn/BOs-Easy-Mob-Farm#17]
### Supporting additional mods

I think it would be really cool to be able to have this compatibility in order to catch any mob and have any Farm be possible, being able to add this in add a modded mobs to it would be nice as well but if you're able to change it to be any that would be amazing also because the item is so expensive having an item that doesn't have luck chance would be cool, I saw it was possible to add the catcher but I currently don't know how to put it into a farm.

**Name and link of the mod**

[This is need to lookup for additional information. Please keep in mind that we are not able to support mods in a alpha status.](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)

### Custom Mob Farm

["forbidden Farm"]
	#Defines after how many seconds a drop is performed.
	#Range: 10 ~ 3600
	desertFarmProcessTime = 300
	#Defines the sound which is played when a loot drop is performed.
	desertFarmDropSound = "minecraft:block.sand.hit"
	#Supported Mobs for the dessert farm.
	desertFarmMobs = all mobs

### Mob Catcher

["Quantum Catcher (Mob Catching Item)"]
	#Defines the luck of capturing the mob e.g. luck of 3 means a change of 1 to 3 to capture a mob. Higher numbers requires more luck. 0 = disable luck.
	#Range: 0 ~ 100
	catchCageSmallMobCatchingLuck = 0
	#Catchable mobs with the Quantum Catcher.
	catchCageSmallMobs = all mobs
[easy_mob_farm-common.txt](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/files/11447455/easy_mob_farm-common.txt)

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. But the request is not 100% clear for me, so I have some follow up questions.

So it seems you want to have a mob farm similar to the "creative mob farm" which is able to catch and handle all kind of mobs. Right ?

If yes, could you add some additional details to your request:

- What is the link with forbidden arcanus ? Should the farm use any items of this mod or just support some of their mobs, if any ?
- Do you have any idea for an expensive recipe for such a mob farm ?
- Any idea how the farm or the Quantum Catcher should look like, I assume similar to the forbidden arcanus style ?

Thanks.

**Comment by FullMetalMaster** [comment]
forbidden arcanus has an item called the Quantum Catcher, it allows you to catch any mob with in the item, I was suggesting compatibility between the two mods in order for you to be able to put the quantum catcher Within any of the farms being able to have a farm of any mob with in reason

**Comment by FullMetalMaster** [comment]
The recipe should probably use something like eyes of ender

**Comment by MarkusBordihn** [comment]
The latest beta supports now mob farms for all kind of mobs and a kind of tier system.
It has still some bugs, so I will try to fix them in the next days to release a stable version.
