### ISSUE TITLE
Game crash when using blaze burner

### ISSUE THREAD

**Issue by clarkeash** [MarkusBordihn/BOs-Easy-Mob-Farm#19]
**Describe the bug**
When I place a blaze burner from the create mod into the nether farm the game crashes. This is a fairly new version of create so maybe that's the cause?

**Additional context**
Minecraft: **1.19.2**
Forge: **43.2.11**
Create: **0.5.1b**
EasyMobFarm: **5.1.0**

**Debugging**
[crash-2023-06-07_21.24.57-client.txt](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/files/11681732/crash-2023-06-07_21.24.57-client.txt)

**Mod List**
<img width="229" alt="Screenshot 2023-06-07 213336" src="https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/1612186/40ad583d-5878-4ae9-923a-f804e0d883a7">

**Comment by MarkusBordihn** [comment]
Thanks for the report. I changed the way how create items are handled to avoid this crash.
This is already fixed for 1.18.2 and the fix for 1.19.2 should be live in the next days.

**Comment by Papaturts** [comment]
I have the same Issue
Open a report an decided to double check
Closed mine pretty quickly after seeing this
Thank you for the quick response to the issue

**Comment by MarkusBordihn** [comment]
This should be fixed for 1.19.2. Let me know if you see any other issues with Create. Thanks.

**Comment by clarkeash** [comment]
Great! Thanks for the quick fix

**Comment by Papaturts** [comment]
Thank you for the quick response
So much appreciated!!!!
