### ISSUE TITLE
Mod file material_elements_19.4-7.1.7.0.jar need language provider javafml:45 or above to load: we have found 44

### ISSUE THREAD

**Issue by Scorpions95** [MarkusBordihn/BOs-Easy-Mob-Farm#21]
**Describe the bug**
Mod file material_elements_19.4-7.1.7.0.jar need language provider javafml:45 or above to load: we have found 44

**To Reproduce**

**Expected behavior**

**Screenshots**
https://i.imgur.com/wKv5I8h.png

**Debugging**
Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

**Additional context**
i have easy mobs mod and material elements

**Comment by MarkusBordihn** [comment]
Thanks for the report, but it seems you are using the wrong "material_elements" file in this case.
According the screenshot your Minecraft client is version 1.19.3, but the file you try to loading is 1.19.4 instead.

The following 1.19.3 file should work as expected:
https://www.curseforge.com/minecraft/mc-mods/material-elements/files/4377715

**Comment by Scorpions95** [comment]
> Thanks for the report, but it seems you are using the wrong "material_elements" file in this case. According the screenshot your Minecraft client is version 1.19.3, but the file you try to loading is 1.19.4 instead.
> 
> The following 1.19.3 file should work as expected: https://www.curseforge.com/minecraft/mc-mods/material-elements/files/4377715

it get me this error too
[Minecraft error.txt](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/files/11824021/Minecraft.error.txt)

**Comment by MarkusBordihn** [comment]
Unfortunately I'm not able to provide any TLauncher support.
In general depending on the used Minecraft version you need to use the following files.

For Minecraft 1.19.4 use the following files:

- https://www.curseforge.com/minecraft/mc-mods/easy-mob-farm/files/4592096
- https://www.curseforge.com/minecraft/mc-mods/material-elements/files/4591583

For Minecraft 1.19.3 use the following files:

- https://www.curseforge.com/minecraft/mc-mods/easy-mob-farm/files/4592106
- https://www.curseforge.com/minecraft/mc-mods/material-elements/files/4377715

If this is still not working I recommend to use the CurseForge launcher instead, which automatically handling such dependencies.
