### ISSUE TITLE
[Mod Support] Name of the Mod ... easy mob farm

### ISSUE THREAD

**Issue by Th3Br0k3nmama** [MarkusBordihn/BOs-Easy-Mob-Farm#22]
### Supporting additional mods

To support additional mods, we need some detail information.
Without these information we are not able to proceed with your request.

**Name and link of the mod**

This is need to lookup for additional information. Please keep in mind that we are not able to support mods in a alpha status.

### Animal / Monster

This sections covers all of the relevant mobs, please note we need the full name of these mobs like `minecraft:cow` and not only `Cow`.

**Ambient Animal**

- e.g. minecraft:bat

**Ambient Water Animal**

- e.g. minecraft:cod

**Hostile Monster**

- e.g. minecraft:zombie

**Hostile Water Monster**

- e.g. minecraft:drowned

**Passive Animal**

- e.g. minecraft:chicken

**Passive Water Animal**

- e.g. minecraft:squid

### Standard Mob Farm

If the animal / monster are fitting in the existing mob farms, please list them below.
Otherwise feel free to suggest a new custom mob farm for the mod for specific animals.

### Custom Mob Farm

If the animal / monster are not fitting in one of the existing mob farms,
please describe how the mob farm for these specific animal / monster should look like.

**Animal Plains Farm**

- e.g. minecraft:chicken

**Desert Farm**

- e.g. minecraft:spider

**Monster Plains Cave Farm**

- e.g. minecraft:cave_spider

**Ocean Farm**

- e.g. minecraft:cod

### Mob Catcher

Did you have any idea about the design of the mob catcher for mobs for the mod.
Please avoid something like a Mob-ball because it's to generic.

firstly i was not sure where to even begin typing so i did so here but secondly, i am, at this time,unable to use any of he provided "mob catchers" to catch blaze or wither skeletons, if you wouldnt mind helping me sole this issue it would be greatly appreciated

**Comment by MarkusBordihn** [comment]
Thanks for the report. On the main page there is a list of mobs and their corresponding catch items / farm.
See: https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm#supported-minecraft-mobs

At the moment there is no "default" mob catcher available for "blaze" or "wither skeletons", but you can use the creative mob catcher or items from other mods. 
If you are using "create" you can use the blaze burner to catch a mob and place it into the farm.

Another possibility is to adjust the config file to add these mob to any mob catching item and / or mob farm, see:
https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm#support-for-additional-mods-%E2%84%B9%EF%B8%8F

**Comment by MarkusBordihn** [comment]
The new beta version includes a tier system, which allows to catch and process any kind of mobs.
Furthermore you can adjust the config file to allow to catch and/or process all kind of mobs.
