### ISSUE TITLE
unable to put insect net into bee hive with productive bees 

### ISSUE THREAD

**Issue by atlasaplo** [MarkusBordihn/BOs-Easy-Mob-Farm#23]
wont let me put in net with iron bug in it

**Comment by MarkusBordihn** [comment]
Could you please let me know the Minecraft version and Productive Bee version were you have this issue? Thanks.

**Comment by Jaheira12** [comment]
I am also experiencing this issue - caught the bee in the insect net but am unable to put it in the farm - note a regular minecraft bee goes in there fine.
I am on Productive bees version: 1.19.2-0.10.7.2
And Easy Mob Farm Version: 1.19.2-5.3.0
I have experienced this issue previously on an earlier version - didn't record that at the time sorry

**Comment by MarkusBordihn** [comment]
Thanks for the report. I took a while to add support for all Bees.
In the latest beta you should be able to capture all kind of Bees and getting the corresponding drop.
Please keep in mind that the beta is still not final and could include some bugs which are fixed in the next release version.
