### ISSUE TITLE
[Mod Support] Cyclic and Alex's Mobs

### ISSUE THREAD

**Issue by Samapoke** [MarkusBordihn/BOs-Easy-Mob-Farm#24]
### Supporting additional mods

Hello, I really hope for a support for Cyclic: https://www.curseforge.com/minecraft/mc-mods/cyclic and Alex's Mobs: https://www.curseforge.com/minecraft/mc-mods/alexs-mobs

Please support mob farms for all the mobs in Alex's mobs

### Mob Catcher

Please add support for Monster Ball from Cyclic 

Ps: And would you also please adding recipe for Creative mob farm and Creative mob catcher?

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. I will implement most of this in the next bigger update together with a tier system.

I haven't used Alex's mobs so far, so I wonder if all mobs are dropping something meaning full or if there are some mobs like the whale which doesn't need to be supported ?

**Comment by Samapoke** [comment]
> Thanks for the feedback. I will implement most of this in the next bigger update together with a tier system.
> 
> I haven't used Alex's mobs so far, so I wonder if all mobs are dropping something meaning full or if there are some mobs like the whale which doesn't need to be supported ?

Yeah you're right, some mobs just don't drop anything... It's will take a lot of time to make a list for Alex's Mobs' mobs. Thank you for the reply.

**Comment by MarkusBordihn** [comment]
No worries I will add some of them per each update, so Cyclic and Alex Mobs are supported in the latest beta version.
After some testing and bug fixing I will release a stable version in the next days.
