### ISSUE TITLE
Nether Stars drops

### ISSUE THREAD

**Issue by x-j0nnay-x** [MarkusBordihn/BOs-Easy-Mob-Farm#25]
hey i was just wondering if its possible to add wither drops?

**Comment by x-j0nnay-x** [comment]
so i added this into loot manager.java

 // Wither Support.
    if (Boolean.TRUE.equals(filteredLootDrops.isEmpty() && COMMON.WitherDropStar.get())
            && mobType.equals(BossMonster.WITHER) && random.nextInt(9) == 0){

      filteredLootDrops.add(new ItemStack(Items.NETHER_STAR));
    }

**Comment by x-j0nnay-x** [comment]
so i added to the commonconfig in your code
      builder.push("Wither Drop Settings");
      WitherDropStar = builder.comment("Enable/Disable Wither drops.")
              .define("WitherDropsStar", false);
      builder.pop();

**Comment by x-j0nnay-x** [comment]
added this to Lootmanager
 // Wither Support.
    if (Boolean.TRUE.equals(filteredLootDrops.isEmpty() && COMMON.WitherDropStar.get())
            && mobType.equals(BossMonster.WITHER) && random.nextInt(9) == 0){

      filteredLootDrops.add(new ItemStack(Items.NETHER_STAR));
    }

**Comment by x-j0nnay-x** [comment]
this seems to have worked, this also means that it does not always drop the star the value can change this way it seems balanced

**Comment by MarkusBordihn** [comment]
Thanks for the feedback and the example. I you want, you could create a PR (Pull Request) for this.
Otherwise I'm happy to implement this in the next update.

**Comment by x-j0nnay-x** [comment]
not good at doing the pull requests
