### ISSUE TITLE
Enchantment support?

### ISSUE THREAD

**Issue by Kiriao** [MarkusBordihn/BOs-Easy-Mob-Farm#29]
Hi, i was wondering if enchantment on sword effect the mob drop? like each level looting increase the chance of killed_by_player loots, or each level of beheading enchantment (from other mod) increase the mob head to drop.

**Comment by MarkusBordihn** [comment]
I added enchantment support for mending, unbreaking, sharpness and looting for the killed_by_player item and loots.
