### ISSUE TITLE
Hope to see what items the creature produces in JEI

### ISSUE THREAD

**Issue by LuoLanXiEr** [MarkusBordihn/BOs-Easy-Mob-Farm#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MarkusBordihn** [comment]
The mod is just using the regular loot tables of the mob for the drops, so you can use something like [Just Enough Resources](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer) to see which kind of items a creature will produce.
