### ISSUE TITLE
not an issue per se but a question

### ISSUE THREAD

**Issue by Vadewolf** [MarkusBordihn/BOs-Easy-Mob-Farm#32]
by default the sword says its consumed per use but if the sword is enchanted with looting and mending and such will that still be a 1 use sword or? cause ure mod looks really neat but if the max enchanted sword still gets consumed after 1 go i legit have to ask

**Comment by MarkusBordihn** [comment]
Thanks for your question. I just implemented the support for mending and unbreaking with the last update today / yesterday.

The sword gets damaged the following:
- No Unbreaking: 0-10 damage
- Unbreaking lvl 1: 0-5 damage
- Unbreaking lvl 2: 0-3 damage
- Unbreaking lvl 3: 0-2 damage

If exp is generated the sword gets repaired between 0 - 10 damage points.

This means if you have a sword with Unbreaking lvl 3, Mending and Looting it could be also generated xp bottles from time to time. But there is no guarantee that the sword gets not fully consume if you have very bad luck with the random generated values and xp drops.

**Comment by Vadewolf** [comment]
but wat im asking is can there be a way added so the sword doesnt get eaten? pretty pls

basically if it has both unbreaking 3 and mending then it wont be eaten but if it doesnt have any enchants then its 100% if unbreaking 1 then 90% unbreaking 2 60% and unbreaking 3 30% without mending if that makes any sense

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. I added a config entry, which allows disabling the damaging of the weapon item over the config file.
The update version should be live in the next few hours.

**Comment by Vadewolf** [comment]
thank you tho to clarify i wasnt saying to fully disable the damage on the sword if its enchanted just that it wont be eaten if its enchanted hehe

**Comment by Vadewolf** [comment]
umm unless im missing something i dont see a config for the sword like u mentioned

**Comment by MarkusBordihn** [comment]
It could take a while until the version is approved by Curseforge, it is version 6.5.0 and the config flag is called `damageWeaponItem`.
