### ISSUE TITLE
cave mob farms are broken

### ISSUE THREAD

**Issue by Vadewolf** [MarkusBordihn/BOs-Easy-Mob-Farm#33]
**Describe the bug**

all 4 versions of the cave mob farms are broken

**To Reproduce**

craft any of the cave mob farms from copper iron gold netherite and then place and mine them up with the matching pickaxe

**Expected behavior**
not to have to recraft the farms
**Screenshots**

**Debugging**
Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

**Additional context**

**Comment by MarkusBordihn** [comment]
Thanks for the report, will roll out the fix in the next days for all versions.
