### ISSUE TITLE
Client Crash: java.lang.IllegalArgumentException: Cannot get property BooleanProperty ...

### ISSUE THREAD

**Issue by Unicron03** [MarkusBordihn/BOs-Easy-Mob-Farm#34]
**Describe the bug**
When i click on a mob farm, my game crash with the same error. I play on a aternos server with my friend on the 1.18.2 minecraft version and i install Forge 40.2.10

**To Reproduce**
1. Craft a mob farm
2. Click on the mob
3. The game crash
![Capture d’écran 2023-09-24 113830](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/110382392/01f34d9c-3c87-4331-a0df-26b6f6c48591)
[crash-2023-09-24_11.32.08-client.txt](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/files/12708190/crash-2023-09-24_11.32.08-client.txt)

**Debugging**
Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

**Comment by MarkusBordihn** [comment]
Thanks for the but report. Unfortunately I'm unable to reproduce the crash on my own servers.
According the crash log the client just found and air block on the client where the server expect an mob farm instead.

I added an additional safety check with version 6.6.0 which should avoid the crash, but if your server is overloaded (< 20 tps) then this is an expected behavior.

Please let me know if the version 6.6.0 (should be live in some minutes) fixes the crash or if you expect any other kind of crashes with it.

**Comment by Florianer** [comment]
:wave: I might just add in this report I think the same error behavior.

```
java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=powered, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:deepslate}
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.20.1-20230612.114412-srg.jar%23346!/:?] {re:mixin,re:classloading}
	at de.markusbordihn.easymobfarm.menu.MobFarmMenu.updateMobFarmDataCache(MobFarmMenu.java:220) ~[easy_mob_farm_1.20.1-6.5.0.jar%23274!/:6.5.0] {re:classloading}
	at de.markusbordihn.easymobfarm.client.screen.MobFarmScreen.m_88315_(MobFarmScreen.java:272) ~[easy_mob_farm_1.20.1-6.5.0.jar%23274!/:6.5.0] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23346!/:?]
```

Think is, I build all the 4 farms (different types) in an older version. If I now try to open them, the game client crashes. Server is still up and running. Now I relog in, click the same farm and the farm GUI opens. I can see a new redstone toggle switch on the right, that weren't there in the last version. I hoped that Click -> Crash -> Click fixed it. So I did it for all 4 farms. Sadly, this is not a permanent fix. With starting at the first farm, it crashed again. So, I started the client again, clicked on the farm. Opened. Removed everything except one loot, broke the farm. Loot dropped. Perfect! So I broke the 3 others as well. Got my loot, but more important my net and cage. I placed the empty farm, clicked and the client crashed.

My server might also be overloaded and ticks behind, but why `minecraft:deepslate`? Behind is glas, underneath is cobblestone. 
[crash-2023-09-25_21.49.29-client.txt](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/files/12718827/crash-2023-09-25_21.49.29-client.txt)
![2023-09-25_21 49 15](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/2761539/c9a1af02-6046-4884-b502-c6bfa65a716f)

**Comment by MarkusBordihn** [comment]
Thanks a lot for the detailed report. I currently patching the fixes to all version for further testing.
I will let you know as soon this is ready. There should be no need to replace any mob-farm, because it seems only a client-side related issue.

**Comment by MarkusBordihn** [comment]
Seems all versions are update now. Please test version 6.6.1 which should resolve this issue. Thanks.

**Comment by Florianer** [comment]
Fix confirmed! The 2 placed mob farms from the screenshot above can now be opened again as well as the 2 farms I had in the inventory and placed them on top. Thx a lot!
