### ISSUE TITLE
some mob drops not dropping 

### ISSUE THREAD

**Issue by Vadewolf** [MarkusBordihn/BOs-Easy-Mob-Farm#37]
**Describe the bug**
as the title says some mob drops dont drop after the latest update that seemed to fix (maybe) the looting bug
**To Reproduce**

**Expected behavior**
all drops to drop pls

**Screenshots**

**Debugging**
Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

**Additional context**

**Comment by MarkusBordihn** [comment]
Thanks for the report. Please check the config file. It could be that it was not updated correctly and some "Disable ..." including the value "true".

If this is not the case please provide a single example and your config file to reproduce the issue. Thanks.

**Comment by Vadewolf** [comment]
i have several mob farms one of chicken one of cow one of pig and one of sheep and everything but the meats are dropping and afaict from my spider creeper and skele ones nothing is dropping

**Comment by Vadewolf** [comment]
ok so further testing seems mutton bones raw chicken and raw beef are bugged afaict

**Comment by Vadewolf** [comment]
oh and spider eyes

**Comment by Vadewolf** [comment]
ok so fixed the issue and came to find out the config was worded in a way that actually screwed up the farms themselves (sry for language) cause the configs are worded in such a way that legit to make them turn on the additional drops is opposite of wat one would normally do

**Comment by MarkusBordihn** [comment]
Thanks for the valuable feedback. I assume that the config system is smart enough to detected changes from the former default values, which seems not do be the case.

I will rename the option names, which should make sure to understand which option is "forcing" or "disable" a specific drop with the next update together with a iron golem farm. ;)

**Comment by Vadewolf** [comment]
thank you so much

**Comment by Vadewolf** [comment]
umm this bug is back again cause now its not dropping correct loot for nether mobs @MarkusBordihn
