### ISSUE TITLE
Allow dynamic filter options for Iron Golem Farm.

### ISSUE THREAD

**Issue by Vadewolf** [MarkusBordihn/BOs-Easy-Mob-Farm#38]
**Is your feature request related to a problem? Please describe.**
the iron golem farm to drop everything like normal iron golem farms do pls

**Describe the solution you'd like**
for the iron golem farm to drop poppies pls

**Describe alternatives you've considered**
easy villager iron farms which are slower and dont give as much per

**Additional context**

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. I always thought that nobody needs to many Poppies but they have some use-cases.
I added a config switch to disable the filter of the iron golem farm.
I just created a fix (and some other issues) and will patch and release all other versions in the next hours / day.
