### ISSUE TITLE
animalPlainsFarmProcessTime not working

### ISSUE THREAD

**Issue by pdrive** [MarkusBordihn/BOs-Easy-Mob-Farm#4]
**Describe the bug**
1. changed animalPlainsFarmProcessTime and monsterPlainsCaveFarmProcessTime to 180. 
2. restart server.
3.  monsterPlainsCaveFarmProcessTime is working correctly and is updated to 180
4.  animalPlainsFarmProcessTime still shows 300

**To Reproduce**
1. Go to easy_mob_farm-common.toml
2. change to animalPlainsFarmProcessTime = 180
5. See error

**Expected behavior**
change the process time. doesnt.

**Additional context**
only have 2 farms so far.
the other one, monsterPlainsCaveFarmProcessTime is working correctly. i changed the time and it works

**Comment by MarkusBordihn** [comment]
Thanks for the report. I was able to reproduce the issue and will fix it in the next version.
In the mean time you can simple remove and add the mob catching item back to the farm to update the processing time.

The processing time will only be updated if you add an mob catching item.
In the case there is already a item in use and the processing time get updated in the config it will still use the old time until the item get replaced or re-set.

**Comment by pdrive** [comment]
> The processing time will only be updated if you add an mob catching item. In the case there is already a item in use and the processing time get updated in the config it will still use the old time until the item get replaced or re-set.

thanks! that works.
