### ISSUE TITLE
🐛Magma Slimes Not Working with Creative or Netherite Mob Farms

### ISSUE THREAD

**Issue by cringoleg** [MarkusBordihn/BOs-Easy-Mob-Farm#44]
#### **Overview**
Despite attempts to get the magma slimes to work with both creative and netherite mob farms, the efforts were unsuccessful. I've looked into issue `#18`, but the solutions provided didn't help in my situation.

---

#### **Testing Setup**
I set up a testing environment with three different sizes of magma cubes:  
![Magma Cube Sizes](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/57872461/2771b15e-6924-4765-b6f3-c3194cb37d00)

**Captured Magma Cubes**:
1. Small (White)  
   ![Small Magma Cube](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/57872461/654f54b0-15af-4613-a542-3db2c4f7cb31)
2. Medium (Green)  
   ![Medium Magma Cube](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/57872461/d1d12d61-e60c-4914-a97c-04b235d282f7)
3. Large (Red)  
   ![Large Magma Cube](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/57872461/bc157650-3e0b-4f64-bf2f-2804fce3c354)

---

#### **Detailed Test Process**
- I used 9 creative farms for each row in the test setup.
- A `netherite sword` with `Looting III` was inserted into each farm.
- The slimes were spawned using spawn eggs and subsequently caught with the creative mob catcher.
- I ensured that killing them manually does drop loot.
- I waited for at least 5 minutes (anticipating 5 drops from each farm) to allow for some RNG. However, no loot dropped from any of the farms.

It's worth noting that whenever a magma cube (regardless of size) is captured with a netherite lasso or similar tool, the `Possible Loot` field doesn't appear.

---

#### **Environment Details**
- Minecraft Version: `1.19.4`
- Mod Version: `6.8.0`

---

**Comment by MarkusBordihn** [comment]
Thanks for the report. It's seems that in newer versions the size information is not correctly passed to the loot manager to get the correct loot.

I will create a fix to pass the missing information to the loot manager and will add a config switch to force a drop regardless of the size like for slimes.

**Comment by MarkusBordihn** [comment]
This should be fixed with 6.9.0 which should be live in the next hours.
