### ISSUE TITLE
🐛Repetitive Warning Message Due to Hopper-Farm Sword Insertion Interaction

### ISSUE THREAD

**Issue by cringoleg** [MarkusBordihn/BOs-Easy-Mob-Farm#46]
#### Description:
When a farm setup has a sword placed within, and a hopper filled with swords tries to transfer items into the farm, a repetitive warning message is triggered. The warning message shown is `Unsupported mob catching Item iron_sword minecraft:iron_sword: {Damage:0}`. This seems to occur due to the hopper attempting to insert a sword into a slot already occupied by a sword, thus failing the transfer and triggering the warning message.

This makes the automated farm refills dangerous to use. I had about 40 messages per second from a single farm.
Due to having about 10 farms while testing automated sword refill system, the server got hung on `[Server thread/INFO] [Framework/]: Unloading server configs...` after the `stop` command.

#### Steps to Reproduce:
1. Establish a farm with a sword in its slot.
2. Position a hopper adjacent to the farm ensuring it's connected to transfer items into the farm.
3. Fill the hopper with swords and observe the console for the warning message.

Mod Version: `6.8.0`

**Comment by cringoleg** [comment]
Tested it with `6.9.0`. Everything's the same.

**Comment by MarkusBordihn** [comment]
Thanks for the report. My fault, seems that I forgot to remove this testing message for troubleshooting some 3rd party mod related issues.
