### ISSUE TITLE
More boxes for loot to drop

### ISSUE THREAD

**Issue by Kiriao** [MarkusBordihn/BOs-Easy-Mob-Farm#47]
Able to increase the boxes for loot to generate? i have looting in my sword now, but the yellow text keep appearing. cuz some mod monster have large loot table and 5 is not enough.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the feedback. You can add a hopper below the farm to store the output in a chest.
Anyways, I could add a tier system for the output slots as well, if this is not working for your use-case.

What do you think should be the max. numbers of output slots for your use-case (e.g. 10 slots)?

**Comment by Kiriao** [comment]
I see there like alot of tier maybe each tier can increase 5-10? the number is random you can change.
