### ISSUE TITLE
bee farm doesnt work 

### ISSUE THREAD

**Issue by Vadewolf** [MarkusBordihn/BOs-Easy-Mob-Farm#48]
**Describe the bug**

vanilla bees do not drop honeycombs

**To Reproduce**

place a vanilla bee in a bee farm

**Expected behavior**

to drop the honeycombs

**Screenshots**

**Debugging**
Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

**Additional context**
info pls

**Comment by MarkusBordihn** [comment]
Please confirm if you set the option "forceBeeDropHoneycomb=true".
If yes, the bee should drop honeycomb with a 1:3 luck.

Mhhh maybe I should remove this 1:3 luck for vanilla mobs.

**Comment by Vadewolf** [comment]
i did and its either worse then 1:3 luck or somethings derped cause its not dropped in atleast 20 minutes js

**Comment by MarkusBordihn** [comment]
20 minutes is a lot of time. 

Please let me know the mod and mc version you are using and I will try to reproduce the issue.
I will additional removing the 1:3 luck for vanilla mobs which should help to eliminate this factor.

**Comment by Vadewolf** [comment]
easy mob farm 6.9.1 on MC version 1.20.1

**Comment by MarkusBordihn** [comment]
Mhhh I'm not really able to reproduce the issue.

![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/9a693e3b-4f73-408e-92bd-3d94cec8a90f)
![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/2c45622a-bacc-49dd-a3cc-dcd54d0afd83)
![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/9906602c-9acc-4ff8-abe8-8d46bbcbdfa4)
![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/2ba4a64c-ef48-4872-89e4-8e3e77a3886e)

The farm worked fine with the lasso, spawn egg and insect net.

I will release the fix which removes the luck from vanilla mobs to see if this fixes the issue.
Maybe you need to re-catch the mob to make sure they are using the correct loot table.

**Comment by Vadewolf** [comment]
will do that thank you
