### ISSUE TITLE
repeat of #37

### ISSUE THREAD

**Issue by Vadewolf** [MarkusBordihn/BOs-Easy-Mob-Farm#49]
**Describe the bug**
https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues/37
**To Reproduce**

**Expected behavior**

**Screenshots**

**Debugging**
Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

**Additional context**

its now happening to nether mobs

**Comment by MarkusBordihn** [comment]
Could you please provide 2-3 example of mobs which are not working as expected?

Some nether mods requires that he mob is in a specific biome and/or dimension to get the correct loot.

**Comment by Vadewolf** [comment]
zombie piglin blaze and wither skeleton for example

**Comment by MarkusBordihn** [comment]
Ok, can't reproduce the issue, they are dropping all of their expected "player killed" loots.

![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/472bae3c-3a6b-4151-99fe-56e4bfabd8e1)
![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/cc87b057-d58c-43d5-a50a-287498760f6f)
![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/764908ef-373f-498c-9c04-d74229365aa1)

I currently adding more "forced" drop options with the possibility to define changes for the drop.

**Any wishes which drops I should add here ?**

At the moment I have:
- forceBeeDropHoneycombChange
- forceBlazeDropBlazeRodChange
- forceChickenDropEggsChange
- forceDrownedDropArmorChange
- forceDrownedDropCopperIngotChange
- forceDrownedDropNautilusShellChange
- forceDrownedDropTridentChange
- forceEndermanDropEnderPearlChange
- forceSlimeDropSlimeChange
- forceMagmaCubeDropMagmaCreamChange
- forceWitherDropNetherStarChange
- forceWitherSkeletonDropWitherSkeletonSkullChange
- forceZombifiedPiglinDropGoldNuggetChange
- forceZombifiedPiglinDropGoldIngotChange
- forceZombifiedPiglinDropWeaponChange

**Comment by Vadewolf** [comment]
only change i can think of is adding specfic farms for certian mobs like the wither and shulker maybe but thats just me seeing wats posted above looks great

**Comment by MarkusBordihn** [comment]
Ok, so version 7.0.0 includes the new changes which allows better control over the drop chances of most of the interesting mobs.
You can force the drop of items if you set the corresponding chance in the config file to 1 which mean 100% drops.

See: https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/wiki/Configuration#forced-drop-chances-
