### ISSUE TITLE
[1.18.2] No Salmon in Ocean Farm

### ISSUE THREAD

**Issue by HalcyonSeas73** [MarkusBordihn/BOs-Easy-Mob-Farm#5]
**Describe the bug**
(Minecraft Vanilla's) Salmon, regardless of capture method, can't be placed in the Ocean farm. They can be placed in the creative farm just fine.

**To Reproduce**
-Try putting a captured Salmon into an Ocean farm.

**Expected behavior:** Salmon working in an Ocean farm, as it is an ocean mob.

![Untitled](https://user-images.githubusercontent.com/84727791/169678947-c6a3aed4-9359-4ca1-bd28-0aa0d470c764.png)

**Comment by MarkusBordihn** [comment]
Thanks for the report, this is fixed in https://www.curseforge.com/minecraft/mc-mods/easy-mob-farm/files/3801369

You need to delete the old "easy_mob_farm-common.toml" from your config folder, so that the new config file with the correct settings could be automatically created.
