### ISSUE TITLE
end mob farms if possible pls

### ISSUE THREAD

**Issue by Vadewolf** [MarkusBordihn/BOs-Easy-Mob-Farm#50]
**Is your feature request related to a problem? Please describe.**

like the title says id love to see an end farm made if possible for farming shulkers or enderman if possible

**Describe the solution you'd like**

**Describe alternatives you've considered**

ars noveau but its difficult to actually get a shulker for the farm 

**Additional context**

this would be so awesome if its doable

**Comment by MarkusBordihn** [comment]
That's doable I already added support for some other mods items like mob catcher, blaze burner, ...
It will only take some time, because I need to design a end mob farm and test things.

**Comment by Vadewolf** [comment]
thank you so much
