### ISSUE TITLE
Bottles cannot be put in the experience compartment in the farm from Easy Mob Farm

### ISSUE THREAD

**Issue by 4u4aaa** [MarkusBordihn/BOs-Easy-Mob-Farm#59]
Bottles cannot be put in the experience compartment in the farm from Easy Mob Farm.

**Comment by MarkusBordihn** [comment]
Could you please provide the following details:

- The used Minecraft and Mod version?
- Which kind of bottles like Experience bottles, empty glass bottles, water bottles, ... ?

Thanks.

**Comment by TleyVi** [comment]
easy_mob_farm_1.20.1-7.0.0 mod version 
Forge Version 47.2.1 Minecraft
'minecraft:glass_bottle'

**Comment by oafx** [comment]
@TleyVi there is a limit which allows only stack sizes of exactly 1 to be put in the farm it seems. Did you try to put a single bottle in the farm?
