### ISSUE TITLE
[1.18.2] Duplicate items via shift click

### ISSUE THREAD

**Issue by erasels** [MarkusBordihn/BOs-Easy-Mob-Farm#6]
**Describe the bug**
Shift-clicking an item out of a farm duplicates it. So if I shift-click a stack of ender pearls, I receive 2 stacks.

**Additional context**
I'm running with two mods that may be a culprit here if this doesn't happen normally, Mouse Tweaks and Inventory Tweaks.
Forge version is 40.1.16

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report, this is fixed in https://www.curseforge.com/minecraft/mc-mods/easy-mob-farm/files/3801369

It was caused by a broken logic for the quick move event and mostly affects only item stack with less than 64 items.
