### ISSUE TITLE
give time for the mob farm to extract items instead of complaining to the user

### ISSUE THREAD

**Issue by Texbio** [MarkusBordihn/BOs-Easy-Mob-Farm#65]
When I am farming modded mobs like the treasure goblin from apotheosis+twilight forest and it has a loot pool of over 100 items, it only gives me 5 of those items. I want everything. I am using the pipes mod to extract items from this block so I should be able to take items out of this very fast, but this mod decides to trash it all...
![image](https://github.com/user-attachments/assets/208b7902-a283-4603-8177-da6b57318fec)

Please either add a buffer system where it will try to restock the 5 slots with the items its not able to take out immediately and maybe add an auto ejecting system to containers. On restarts you maybe can clear this buffer since I doubt it is being heavily tracked by players. I want my items :(

**Comment by MarkusBordihn** [comment]
Thanks for the feedback.

I'm currently working on a new version of the 'Easy Mob Farm,' which will have fewer restrictions and be available for Fabric, Forge, and NeoForge.

This version will not have a direct buffer (like the current 5 output slots) and will allow for more automation than before.

Unfortunately, it will take a little more time to adapt this new version for all mod loaders.
