### ISSUE TITLE
Allow hoppers to feed items into the farm

### ISSUE THREAD

**Issue by Greenfire44Official** [MarkusBordihn/BOs-Easy-Mob-Farm#68]
**Is your feature request related to a problem? Please describe.**
Hoppers can't feed items into the farms

**Describe the solution you'd like**
Allow hoppers to feed items like empty bottles and weapons into the farm to allow for full automation of the farms

**Describe alternatives you've considered**
For the bottles, there could be an extra slot for the bottles that allow for a full stack of bottles to be added and another for the bottles o' enchanting, the empty bottles would be consumed one by one and the bottles o' enchanting would accumulate on their own slot.

**Additional context**
I dislike how complex some automation mods can be which why I like the simplicity of this mod, however it's not fully automatic which is why I want the farms to be fully automatable with the vanilla hoppers without the use of extra mods.
I play on 1.20.1.

**Comment by MarkusBordihn** [comment]
I'm currently working on a new version of the 'Easy Mob Farm,' which will have fewer restrictions and be available for Fabric, Forge, and NeoForge.

This version will not have a direct buffer (like the current 5 output slots) and will allow for more automation than before.

Unfortunately, it will take a little more time to adapt this new version for all mod loaders.
