### ISSUE TITLE
i dont understand how the xp upgrade works

### ISSUE THREAD

**Issue by useremem** [MarkusBordihn/BOs-Easy-Mob-Farm#73]
I have built a basic cave mob farm(also the ingame name for that farm is absolutely broken) and when i put in the xp upgrade it just does not collect xp

**Comment by MarkusBordihn** [comment]
Thank you for the feedback! The XP upgrade only activates if the mob can actually drop experience. 
So, for example, if a mob can drop at least 3 experience points, there’s a 1 in 10 chance that an experience bottle will drop.

With the latest update, I’ve added additional help texts and made it possible to adjust the 1:10 drop chance in the mob_farm_config.cfg file.
