### ISSUE TITLE
exp card doesnt work

### ISSUE THREAD

**Issue by Vadewolf** [MarkusBordihn/BOs-Easy-Mob-Farm#75]
💡 Check the
[Bug Tracker](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues?q=label%3Abug)
and [Crash Tracker](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues?q=label%3Acrash)
before
reporting a new issue.
There you can find a lot of useful information and solutions for common problems.

**Note**:
Please make sure to fill out the following template to the best of your ability. This will help us
to identify and fix the issue faster.
using the exp card which has a 1 in 10 chance for bottles of xp doesnt drop any of them and no way to even use bottles at all

**Minecraft and Mod version** 🐞
The used Minecraft and Mod version.
1.20.1 8.4.0

**Describe the bug** 🐞

**To Reproduce** ⚙️

**Expected behavior** ✔️

**Screenshots** 📸

**Debugging** 🛠️
Before reporting an issue, please enable the debug mode over `/easy_mob_farm debug log true` to get
more
detailed information about the issue in the logs.
Additionally, check if there is anything relevant in the crash-reports, debug.log, and latest.log
file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)** 🧩

**Additional context** 📝
pls fix or tell me wat im doing wrong

**Comment by MarkusBordihn** [comment]
Thank you for the feedback! Could you please provide an example of the mob you’re trying to get XP drops from?

In general, there is a 1 in 10 chance for an XP drop, and the mob must drop at least 3 XP orbs for it to count. If the mob drops only 2 XP orbs, the drop is ignored. This means that mobs dropping 1-3 XP orbs have a much lower drop rate compared to those that consistently drop 3-6 XP orbs.

However, with the latest update, you can adjust the drop chance in the config file to increase the drop rate if needed.

**Comment by Vadewolf** [comment]
zombie pig cow sheep chicken spider and wilden hunter but none dropped xp at all after like 4 hours of it running

**Comment by MarkusBordihn** [comment]
Thank you for providing the details! In this case, most of the listed mobs require a **"player kill"** to drop experience orbs.

Could you please check your log files for any messages like the following?  
```
"Unable to get experience reward {...} for entity {...} due to {...}!"
```

If you find this message, kindly share your exact Minecraft version and mod loader (Fabric, Forge, or NeoForge).

In the next update, I’ll adjust the logic to automatically improve the drop chances and provide more detailed information about the possible drops for the mob being used. 
Thank you for helping to improve the mod!

**Comment by Vadewolf** [comment]
1.20.1 forge for modloader and been checking but nothing like that shows also i thought the sword upgrade counted as a player kill otherwise thats busted too
