### ISSUE TITLE
Game Crash 

### ISSUE THREAD

**Issue by DJ1Silva** [MarkusBordihn/BOs-Easy-Mob-Farm#8]
**The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Registry Object not present: minecraft:empty
Exit Code: -1**

[crash-2022-06-18_22.52.56-client.txt](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/files/8934113/crash-2022-06-18_22.52.56-client.txt)

**Comment by MarkusBordihn** [comment]
Thanks for the report, but unfortunately you are not using the latest version of the mod and/or forge.
Please use the latest version of the mod which has a hard requirement for Forge 41.0.38.

According the log file there is an issue with some fluid textures, but my mod is not using any fluid textures or fluid at all.
See: https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/search?q=fluid

So it looks like that this crash is caused by some other mods which displays fluid information or render fluids textures.
It could be also related to resource packs, which are not optimized for 1.19 yet.
I say similar crashed with 1.19 with Jade or other mods which displaying object information.

**Comment by DJ1Silva** [comment]
> Thanks for your quick answer i download Forge 41.0.38 and remove all of my mods but still game crash
[crash 42.txt](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/files/8934232/crash.42.txt)

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. I tried to reproduce the issue, also with some of your enabled resource packs like "Stylized Potions", but was not able to.

You should also remove some of the resource packs which are not compatible with 1.19 like [Stylized Potions](https://www.curseforge.com/minecraft/texture-packs/stylized-potions), which requires optiFine, but as far as I know there is no optiFine 1.19 version available yet.

Could you please provide me a screenshot of the remaining mods in  your "mods" folder, like:

![image](https://user-images.githubusercontent.com/12183293/174456471-59336eaa-d7bc-45ae-a17c-46b8230a25e8.png)

I also found a similar crash log, which also mentioned that this is related to the new potion system:
https://forums.minecraftforge.net/topic/112619-forge-119-crashes-before-getting-to-main-menu/

As already mentioned the mod is not using any potions so it's very unlikely that the crash game from this mod, but I will run some tests on other PC's just to make sure I don't overlook something.

**Comment by DJ1Silva** [comment]
> this is my mod folder i remove all of my mods and disable my resource packs but game still crash 
![image](https://user-images.githubusercontent.com/107769294/174465487-3f78c6a4-ce2a-4b43-8aab-3b927d523ebf.png)

**Comment by MarkusBordihn** [comment]
Thanks a lot for the screenshot. I was able to reproduce the issue and the error message is not really matching with the real issue.

![image](https://user-images.githubusercontent.com/12183293/174479942-10ff5c70-283a-4ba8-9fd4-f33af23c70fd.png)

The mod requires [Material Elements](https://www.curseforge.com/minecraft/mc-mods/material-elements) to working. Normally you get an error that an dependency is missing, but it seems that this is broken in the current Forge version and it displays this random crash instead.

After installing both mods, the error message disappears for me.

![image](https://user-images.githubusercontent.com/12183293/174479978-7793532c-b214-4f58-bc40-c98c595b465f.png)

**Comment by MarkusBordihn** [comment]
Submitted an error report for Forge 1.19: https://github.com/MinecraftForge/MinecraftForge/issues/8772
