### ISSUE TITLE
[Crash] Client Crashing while attempting to render mob cards

### ISSUE THREAD

**Issue by CardKaiser** [MarkusBordihn/BOs-Easy-Mob-Farm#80]
**Minecraft and Mod version** 🐞
1.20.1 easy_mob_farm-forge-1.20.1-8.5.0.jar from Monumental Experience-2.0.82

**Description of the crash** 💥
The server recently updated the Easy Mob Farms mod to 8.5 and now any container with a mob card inside of it will crash the client to desktop.  Crash occurred while opening an Ars Noveau repository that contained a mob card.  Another crash happened after picking up a mob card and attempting to access my player inventory.  

**Steps to reproduce the crash** ⚙️

1. Place mob card inside of an inventory
2. Access the inventory

**Expected behavior before the crash** ✔️
View the inventory as normal.

**Logs** 📝

https://gist.github.com/CardKaiser/304237fca300c71ccbea8046475d0f45

[2024-11-21-6.log.gz](https://github.com/user-attachments/files/17861120/2024-11-21-6.log.gz)

[latest.log](https://github.com/user-attachments/files/17861164/latest.log)

To speed up the diagnosis, please provide the following files if possible:

- `logs/debug.log`
- `logs/latest.log`
- `crash-reports/crash-...txt`

[These logs contain essential details that will help me identify the problem and offer more accurate
assistance.
You can upload the logs to https://gist.github.com/ or https://mclo.gs/ and share the link here.]

**Additional context** 📋
Add any other context or information about the crash here.

**Comment by MarkusBordihn** [comment]
Thank you very much for your detailed report! 
This issue should be resolved in version 8.5.1, along with several other minor fixes and improvements.
