### ISSUE TITLE
[Feature Request] Anything Special for Magma Cubes?

### ISSUE THREAD

**Issue by Routhinator** [MarkusBordihn/BOs-Easy-Mob-Farm#84]
I'm wondering if I'm missing something with regard to Magma Cubes... I have had this farm running for an hour and I've gotten nothing so far. I know the magma cream drop rate is low, however this seems really low given the luck upgrade. 

I think the experience drop is too low for that upgrade so I'll remove that. But I think I may be missing something with the other drops.

Related topic, the Info dialog _might_ have a typo if I'm reading that correctly:

> To low experience

To = Directed to, addressed to
Too = excessive, beyond a threshold

![2024-11-23_15 53 44](https://github.com/user-attachments/assets/e2129d80-f981-486b-bce7-d855611bb543)
![2024-11-23_15 53 48](https://github.com/user-attachments/assets/19d8e67e-2009-4637-8c91-4f88fabe1827)

**Comment by Routhinator** [comment]
Also - might be worth opening the new "Discussions" feature for questions to avoid issue pollution.

**Comment by Routhinator** [comment]
Hmmm, is this somehow related to https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues/44 ?

**Comment by MarkusBordihn** [comment]
Thank you for the report! I can confirm that magma cream drops are working as expected in my tests. 

https://github.com/user-attachments/assets/e1e0d7b8-8865-4b37-966e-4b07fd581caa

![image](https://github.com/user-attachments/assets/5e637eee-5e8b-446a-8ad0-fe5cdf860f91)

However, it’s important to note that the Mob Capture Card must be dropped by the smallest magma cubes. 
If the card is from larger magma cubes, they won’t drop magma cream.

The linked issue isn’t directly related. In the latest version, I’ve completely rewritten the mob farm system to automatically handle all entity data, unlike previous versions, which only accounted for specific cases.

This rewrite might explain the issue in your case: when the Mob Capture Card is from larger magma cubes, their loot table doesn’t include magma cream.

I’ll convert this into a feature request to improve clarity for players.

**Comment by Routhinator** [comment]
Ahh interesting. I got this from the loot table. Should the card be removed from the loot table of all but the smallest cubes then?

**Comment by MarkusBordihn** [comment]
Mob cards are not dropped through loot tables, as I aim to avoid creating multiple loot table files.

* In the short term, I will disable mob card drops for larger magma cubes, as you suggested.
* In the long term, I plan to factor in mob size for the capture cards, allowing players to obtain different cards based on the mob's size.

**Comment by Routhinator** [comment]
Hmm something else seems off here. :thinking:  I got another Magma Cube card, and this time I am positive it came from the smallest cube. Same cube dropped a magma cream. And based on the size of the mob in the machine, it appears the first one was as well? At any rate.. still no drops.
![2024-11-23_18 49 54](https://github.com/user-attachments/assets/6779bbb4-58db-4386-9603-b8cfee3dc8e5)

**Comment by MarkusBordihn** [comment]
Thank you for following up. I've implemented some changes to make the mob size for Magma Cubes and Slimes more visible, along with several other general improvements.

![image](https://github.com/user-attachments/assets/10af48c5-c2c4-4078-9065-2e5fda4e4c78)

These updates include a "Creative Speed Enhancement" for testing, which generates drops every 4–5 seconds to simplify troubleshooting and testing processes.

Additionally, a bonus drop mechanic has been added for specific scenarios, such as placing bees in a bee farm or Magma Cubes in a Nether Fortress. These bonus drops are triggered regardless of mob size.

I expect these changes to be ready within the next 1–2 days. They should resolve the issue and make troubleshooting cases like this much easier.

**Comment by Routhinator** [comment]
Excellent, that sounds very helpful thank you! I had been digging around other issues and found the `/data get entity @s SelectedItem` command and was examining that but admittedly could not tell where the cube variant data was in the meta object. `Size: 0` was the only that looked close - but whether that meant tiny or was even related to the cube was unclear without a schema definition.

![2024-11-24_10 04 51](https://github.com/user-attachments/assets/0c8fac12-e557-47a7-8c0c-9960da006bbb)

**Comment by Routhinator** [comment]
Can confirm that this is working! Thanks for all the hard work!
