### ISSUE TITLE
[Bug] UX Issue with Farm UI - Shift+Click does not act upon items in farm inventory

### ISSUE THREAD

**Issue by Routhinator** [MarkusBordihn/BOs-Easy-Mob-Farm#85]
**Minecraft and Mod version** 🐞
Minecraft: 1.20.1
Easy Mob Farm: 8.5.1

**Describe the bug** 🐞
When in a Mob Farm UI, shift+click does not interact with the items at all. User expectation is that shift+click should transfer the item(s) in that slot to the first available slot in the player inventory. Currently the player is forced to click on the items and manually move it which becomes tedious until automation can be achieved.

**To Reproduce** ⚙️

1. Go to a Mob Farm and right click
2. Shift+Click on any item or stack of items, nothing will happen.

**Expected behavior** ✔️
User expectation is that shift+click should transfer the item(s) in that slot to the first available slot in the player inventory.

**Screenshots** 📸
Not sure a screenshot will help here, I can provide video if required.

**Debugging** 🛠️
No crash with this interaction or error log.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)** 🧩
Same pack and version as other issues https://modrinth.com/modpack/magpunkrpg/version/9cUhQeG6

**Comment by Routhinator** [comment]
A note seperate from the bug. I apologise for so many issues in so short a time. First time using the mod and with the Beta label I presume feedback is important. Thank you for being so responsive and helpful.

**Comment by MarkusBordihn** [comment]
> A note seperate from the bug. I apologise for so many issues in so short a time. First time using the mod and with the Beta label I presume feedback is important. Thank you for being so responsive and helpful.

No worries at all, and thank you for your detailed reports! 
I really appreciate the feedback, as I primarily use Forge and NeoForge myself, so it's incredibly helpful to learn about issues that occur in other mod packs and with different mod loaders. 
Your insights are invaluable, especially for the beta, where feedback like yours is essential for polishing the mod. 
Thank you for taking the time to test it and share your experiences! 😊

**Comment by Routhinator** [comment]
>  I primarily use Forge and NeoForge myself

This comment made me realize that as well detailed as I tried to make these, the template is missing a field for mod loader in the context of the issue and I neglected to clearly define that outside providing the pack link. :thinking:

**Comment by Routhinator** [comment]
A note here that I've seen the new PR go in! :partying_face: 

I'll be able to pick up the new version and test it out on Wednesday, then will circle back and close issues.

**Comment by MarkusBordihn** [comment]
Unfortunately, I discovered some additional bugs that need to be addressed before releasing the next version. 
As a result, it's more likely that the next version will be ready by the end of the week.
