### ISSUE TITLE
[Feature Request] Egg Collector Upgrade for Chickens

### ISSUE THREAD

**Issue by Routhinator** [MarkusBordihn/BOs-Easy-Mob-Farm#87]
**Is your feature request related to a problem? Please describe.** 🤔
Currently there is no way to get eggs from a chicken in a mob farm. While I could add another farm and just harvest eggs from the ground, it seems sensible, given the presence of the sheep shearing enhancement, that there is a similar one for egg collection.

**Describe the solution you'd like** 💭
I would like to see an enhancement item for harvesting eggs. Suggested recipe:

N | N | N
E | H | E
N | N | N

N = Nether Quartz
E = Egg
H = Hopper 

**Describe alternatives you've considered** 🔄
No alternative using the mod, would need to setup a pen and devise a way to harvest items from the ground.

**Comment by Routhinator** [comment]
Thanks for adding this so quickly @MarkusBordihn 

One immediate thing I noticed though after this update, is that eggs are now being collected _even without this upgrade_ - My existing chicken farm just started outputting eggs without me ever crafting the item. Is this expected? :thinking:

**Comment by MarkusBordihn** [comment]
Thank you for the feedback! In the latest update, I introduced bonus drops. 
This means that when a mob is used in the correct farm type, it may produce bonus drops. 
These drops are extremely rare by default but can be adjusted in the configuration file if necessary.

In your case, it’s expected that chickens will drop eggs in the Animal Plains Farm but not in other types of farms. 
However, the drop rate depends on the farm's tier and is always lower than what the Egg Collector Upgrade provides.

**Comment by Nikdied** [comment]
Hello

I'm very sorry that I comment on a problem that was fixed more than a year ago, but I play with the Mod in the new Modpack Create Ultimate Selection 2 and I have a problem with the egg-drops. It seems like, that I only get one egg every 2-3 drop-cycles even with the egg collector. A chicken drops an egg every 5-10 minutes, so it's way better to build a vanilla egg-farm. Do you think, you could change the probabilities to like 1-2 eggs every drop-cycle?

Thank you and happy christmas!!🎄🎁
