### ISSUE TITLE
3 mod failed to load correctly

### ISSUE THREAD

**Issue by Scorpions95** [MarkusBordihn/BOs-Easy-Mob-Farm#9]
[crash-2022-07-16_16.53.31-fml.txt](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/files/9125932/crash-2022-07-16_16.53.31-fml.txt)
Also see this picture
https://i.imgur.com/vttZpHz.png
[latest.log](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/files/9125933/latest.log)

**Comment by MarkusBordihn** [comment]
Thanks for the report. Unfortunately with 41.0.94 there were a lot of changes, for this reason only specific mods version will work.
In this case, please make sure to install the latest version of the mods like:

- easy_mob_farm_1.19-2.3.0.jar
- material_elements_1.19-4.3.0.jar
- Optional: material_elements_armor_tools_weapons_1.19-4.3.0.jar
- Optional: material_elements_decorative_1.19-4.3.0.jar

Let me know if you still run into issue, after using the latest versions.
