### ISSUE TITLE
[Bug] Farms become tier 0

### ISSUE THREAD

**Issue by Gn132** [MarkusBordihn/BOs-Easy-Mob-Farm#90]
**Minecraft and Mod version** 🐞
Fabric 1.21.1, easy mob farm 8.6.2

**Describe the bug** 🐞
Any farms crafted (tier 0-3) when placed become tier 0 (1, 2 screenshot). Breaking them gives you tier 0 farm.

**To Reproduce** ⚙️
Craft tier 2 farm, place it. Open it - UI shows Tier 0. Break it. You got tier 0 back.

**Expected behavior** ✔️
When placed and broken you get your tier back.

**Screenshots** 📸
Tier 2 Piglin farm ![image](https://github.com/user-attachments/assets/5fb54efe-f83b-4439-8fda-499bf603fa53)
Tier 2 Piglin farm UI ![image](https://github.com/user-attachments/assets/f9a5ca26-aa32-4ee2-993b-a9c632301ec1)

**Comment by Gn132** [comment]
Also Piglins and Piglin brutes doesnt give any drops at all (even with sword and/or XP addons) but i guess its for another ticket?

**Comment by MarkusBordihn** [comment]
Thank you for the report! This issue was a mistake on my part during the last code refactoring. 
It should now be fixed, and I’ve also added automated tests to help prevent similar issues in the future.
