### ISSUE TITLE
[Crash] accidentally put the skeleton in the farm animal template...

### ISSUE THREAD

**Issue by vempdotcom** [MarkusBordihn/BOs-Easy-Mob-Farm#91]
once i put it in  my game immediately crashes and  continues to anytime i try opening the world... eventually i just disable the mod and open the world and  that fixes it but everything the mod included is wiped so :/
im just nervous to even try putting anything in them but idek where these cards go

**Comment by MarkusBordihn** [comment]
Thank you for the report! Could you please share more information about this issue, such as the crash log or error log that is automatically generated when a crash occurs?

With the crash log, I can pinpoint the exact issue and determine what caused the problem.

Technically, all mob farms are based on the same block. This means the mob farm doesn’t differentiate whether you put a monster in a non-monster farm. The only difference might be that the loot yield is lower compared to using the appropriate farm for that type of mob.

**Comment by KudanaVadmont** [comment]
Hi, I have been crashing because of this. 
[06:26:20 INFO]: Set owner for mob farm block entity to class_3222['Juit'/22344, l='ServerLevel[world]', x=291.40, y=123.00, z=55.45]

Instantly crashes us.  Not sure what to do to fix it.

**Comment by MarkusBordihn** [comment]
Maybe related to #93 ?
