### ISSUE TITLE
[Bug] unable to connect to pipe from other mods

### ISSUE THREAD

**Issue by PinkaLulan** [MarkusBordihn/BOs-Easy-Mob-Farm#94]
**Minecraft and Mod version** 🐞
The used Minecraft and Mod version.
1.21.1 neoforge 21.1.83
easy mob farm 1.21.1-8.6.3

**Describe the bug** 🐞
pipe unable to connect to mob farm block

only minecraft hopper work now

**To Reproduce** ⚙️
1. place mob farm block
2. place pipe

**Screenshots** 📸
none of these pipe works
immersive engineering / modern dynamics / modern industrialization / mekanism / ae2
![2024-12-08 16_10_51-Greenshot](https://github.com/user-attachments/assets/b7384fb4-9a09-4d45-a3ae-eb8a67d1f567)

**Comment by MarkusBordihn** [comment]
Thank you for your report! It seems that NeoForge requires an additional `ItemHandler`. A fix is currently in progress and should be available within the next few hours.

![image](https://github.com/user-attachments/assets/ec15b10d-8dbb-4199-9798-251a9ffaac18)
