### ISSUE TITLE
[Question/Feature] Denied/Blacklisted Mobs

### ISSUE THREAD

**Issue by Dalethium** [MarkusBordihn/BOs-Easy-Mob-Farm#95]
Is there a way to blacklist mobs or only enable specific mobs instead of just having all mobs enabled by default?

I'm unable to find any settings related to a blacklist or white list, and all mobs seem to be dropping their cards.

I do apologize if this is a waste of time for you and I really appreciate your work on this mod.

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. This feature will be available in the next version 8.8.x.

For more details, visit: 
https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/wiki/MobCaptureCard#-allow-and-deny-lists
