### ISSUE TITLE
[Feature Request] Add normal squid to capture card list

### ISSUE THREAD

**Issue by G4m3rkitty3** [MarkusBordihn/BOs-Easy-Mob-Farm#96]
💡 Check the [Wiki](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/wiki) and
[Feature Request Tracker](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues?q=label%3Aenhancement)
before reporting a feature request.
There you can find a lot of useful information and solutions for common problems.

**Is your feature request related to a problem? Please describe.** 🤔

I'm happy that glow squid were added to the capture card list, however...what about just squid? I found it frustrating to go on a wild hunt for squid only to find they've zero card.

**Describe the solution you'd like** 💭

Please add the normal squid to the card capture list!

**Describe alternatives you've considered** 🔄

Just squid?

**Comment by MarkusBordihn** [comment]
Thank you for the feedback! I’ll include a squid capture card design in the next update. 

If you have 2-3 other card designs you’d like to see added, feel free to let me know, and I’ll consider including them as well!

**Comment by G4m3rkitty3** [comment]
No problem! Happy to help! 

Normal Squid, Zombified piglin ( I added zombified since plain piglins drop absolutely nothing when killed except random gear) are currently the only two pressing ones, and have manually (not so gracefully) added to my config file for my current play through.

Ones that could possibly be fun: Wither, Dragon, Warden
